sudo: false

language: ruby
rvm:
  - 2.1

cache:
  directories:
  - vendor
before_cache:
- rm -rfv vendor/.installed  # force gems to refresh

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true  # speeds up installation of html-proofer

install:
- bash checkinstall.sh

